apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
data:
  Caddyfile: |
    lewa.within.website:8080 {
      tls off
      errors stdout

      root /srv/http/lewa
    }

    graphviz.christine.website:8080 {
      tls off
      errors stdout

      root /srv/http/graphviz
    }

    tulpanomicon.guide:8080 {
      tls off
      errors stdout

      root /srv/http/tulpanomicon
    }

    xena.greedo.xeserv.us:8080 {
      tls off
      errors stdout

      header / X-Clacks-Overhead "GNU Ashlynn"

      root /srv/http/xena.greedo.xeserv.us
      markdown / {
        template blog templates/blog.html
        template index templates/index.html
      }

      browse
    }

    xn--u7hz981o.ws:8080 {
      tls off
      errors stdout

      header / X-Clacks-Overhead "GNU Ashlynn"

      internal /templates

      root /srv/http/xn--u7hz981o.ws
      markdown / {
        template index templates/index.html
        template page templates/page.html
      }
    }

    when-then-zen.christine.website:8080 {
      tls off
      errors stdout

      root /srv/http/when-then-zen.christine.website

      internal /README.md
      internal /templates
      internal /LICENSE
      internal /Caddyfile

      ext .md

      browse /bonus
      browse /meditation /srv/http/when-then-zen.christine.website/templates/index.html
      browse /skills /srv/http/when-then-zen.christine.website/templates/index.html

      markdown / {
        #template templates/page.html
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      volumes:
        - name: config
          configMap:
            name: caddy
        - name: lewa
          persistentVolumeClaim:
            claimName: lewa
        - name: graphviz
          persistentVolumeClaim:
            claimName: graphviz
        - name: greedo
          persistentVolumeClaim:
            claimName: xena-greedo
        - name: tulpanomicon
          persistentVolumeClaim:
            claimName: tulpanomicon
        - name: xn--u7hz981o
          persistentVolumeClaim:
            claimName: xn--u7hz981o--2
        - name: when-then-zen
          persistentVolumeClaim:
            claimName: when-then-zen
      initContainers:
        - name: "graphviz"
          image: ghcr.io/xe/x/git
          volumeMounts:
            - mountPath: "/srv/http/graphviz"
              name: graphviz
          command: 
            - sh
            - "-c"
            - |
              cd /srv/http/graphviz
              git clone https://github.com/dreampuf/GraphvizOnline site ||:
              cd site && git pull
        - name: "when-then-zen"
          image: ghcr.io/xe/x/git
          volumeMounts:
            - mountPath: "/srv/http/when-then-zen.christine.website"
              name: when-then-zen
          command: 
            - sh
            - "-c"
            - |
              cd /srv/http/when-then-zen.christine.website
              git clone https://github.com/Xe/when-then-zen site ||:
              cd site && git pull
      containers:
        - name: caddy
          image: ghcr.io/xe/x/caddy1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: "/app/etc"
              name: config
            - mountPath: "/srv/http/lewa"
              name: lewa
            - mountPath: "/srv/http/xn--u7hz981o.ws"
              name: xn--u7hz981o
            - mountPath: "/srv/http/xena.greedo.xeserv.us"
              name: greedo
            - mountPath: "/srv/http/tulpanomicon"
              name: tulpanomicon
            - mountPath: "/srv/http/when-then-zen.christine.website"
              name: when-then-zen
              subPath: site
            - mountPath: "/srv/http/graphviz"
              name: graphviz
              subPath: site
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  selector:
    app: caddy
  ports:
    - port: 80
      targetPort: 8080
      name: http
