apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
data:
  Caddyfile: |
    lewa.within.website:8080 {
      tls off
      errors stdout

      root /srv/http/lewa
    }

    xena.greedo.xeserv.us:8080 {
      tls off
      errors stdout

      header / X-Clacks-Overhead "GNU Ashlynn"

      root /srv/http/xena.greedo.xeserv.us
      markdown / {
        template blog templates/blog.html
        template index templates/index.html
      }

      browse
    }

    xn--u7hz981o.ws:8080 {
      tls off
      errors stdout

      header / X-Clacks-Overhead "GNU Ashlynn"

      internal /templates

      root /srv/http/xn--u7hz981o.ws
      markdown / {
        template index templates/index.html
        template page templates/page.html
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      volumes:
        - name: config
          configMap:
            name: caddy
        - name: lewa
          persistentVolumeClaim:
            claimName: lewa
        - name: greedo
          persistentVolumeClaim:
            claimName: xena-greedo-xeserv-us
        - name: xn--u7hz981o
          persistentVolumeClaim:
            claimName: xn--u7hz981o
      containers:
        - name: caddy
          image: ghcr.io/xe/x/caddy1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: "/app/etc"
              name: config
            - mountPath: "/srv/http/lewa"
              name: lewa
            - mountPath: "/srv/http/xn--u7hz981o.ws"
              name: xn--u7hz981o
            - mountPath: "/srv/http/xena.greedo.xeserv.us"
              name: greedo
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  selector:
    app: caddy
  ports:
    - port: 80
      targetPort: 8080
      name: http
---
