apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: when-then-zen
spec:
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: when-then-zen
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - when-then-zen.christine.website
      secretName: when-then-zen-public-tls
  rules:
    - host: when-then-zen.christine.website
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: caddy
                port:
                  name: http
