apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xn--u7hz981o
spec:
  storageClassName: "itsuki"
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xn--u7hz981o
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - xn--u7hz981o.ws
      secretName: xn--u7hz981o-ws-public-tls
  rules:
    - host: xn--u7hz981o.ws
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: caddy
                port:
                  name: http
