apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  selector:
    app: znc
  ports:
  - port: 80
    targetPort: 1337
    name: http
  - port: 6667
    targetPort: 6667
    name: irc
  type: ClusterIP