nguage: go

go:
  - 1.7.x
  - 1.8.x
  - master

branches:
  only:
    - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go vet -v .
  - go build -v .
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
