apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pt-dh-internal
  namespace: default
spec:
  secretName: pt-dh-internal-tls

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - pt-dh.int.xeserv.us
  issuerRef:
    name: "letsencrypt-prod"
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pt-dh
spec:
  endpoints:
    - dnsName: pt-dh.int.xeserv.us
      recordTTL: 3600
      recordType: A
      targets:
        - 10.211.44.197
