apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pt-dh-internal
  namespace: default
spec:
  secretName: pt-dh-internal-tls

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - pt-dh.default.svc.alrest.xeserv.us
  issuerRef:
    name: "letsencrypt-prod"
    kind: ClusterIssuer
    group: cert-manager.io