apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: headscale
  labels:
    app.kubernetes.io/name: headscale
    app.kubernetes.io/instance: headscale
    app.kubernetes.io/service: headscale
spec:
  selector:
    matchLabels:
      app.kubernetes.io/service: headscale
      app.kubernetes.io/name: headscale
      app.kubernetes.io/instance: headscale
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 10s
