apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: onions
spec:
  acme:
    email: me@xeiaso.net
    server: https://acme.api.acmeforonions.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: onions-acme-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
