schema = 3

[mod]
  [mod."cirello.io/goherokuname"]
    version = "v0.0.0-20190914093443-b436bae8c2c5"
    hash = "sha256-wguSCVwaeRdkHEQOQrdHw7YrVMXfSGtJu4FdmMq7WuI="
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0-rc.1"
    hash = "sha256-3DboBqby2ejRU33FG96Z8JF5AJ8HP2rC/v++VyoQ2LQ="
  [mod."github.com/McKael/madon/v2"]
    version = "v2.0.0-20180929094633-c679abc985d6"
    hash = "sha256-cU5f+sKEVjNSu3gJgp7H2r6VIzhouKNRPeWYih1pdAg="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.0"
    hash = "sha256-TQ0AvXZfuT3PDnb4p/h5zmyT8m9VPcwxlXMJuVD6ltE="
  [mod."github.com/akutz/memconn"]
    version = "v0.1.0"
    hash = "sha256-WOs/RQYjQbn41ui8ztHgWSd4jxydE+fvIrl/0dmHD9Y="
  [mod."github.com/alexbrainman/sspi"]
    version = "v0.0.0-20210105120005-909beea2cc74"
    hash = "sha256-sMY9gSeRWqKE0JwY4HbUF1KO9eaL/hQ/A/uoyr0hrQI="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.44.187"
    hash = "sha256-tPHYtKw84Zxzz5KvEywXNVa6exXrGQRvgSzygBIyxFE="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.17.3"
    hash = "sha256-xIrnSX6lC4i5bhTGZ5clKabpUhDTLMLTN5rLH1YIjM8="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.11.0"
    hash = "sha256-NPbfhtkzFtwdFeXjyLpKOoB1jcqWCC91OozkdIxp9uA="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.6.4"
    hash = "sha256-OWsHeqRByhr3hRQHvOQAnOuxU6LCIJqS+YCwVJG8XfE="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.8.2"
    hash = "sha256-BLzGxsh497qe1jkbBde0AaPk6PlCIot61wqnXk/kPCM="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.1.27"
    hash = "sha256-hnqhkE5p7yw2Ypto+G960nfxHLhGj4R1GZvCVU/vo4E="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.4.21"
    hash = "sha256-N0ALtvhxTZl9XgIff+GqLEvBZZlNxiIFgrEXzMASGDU="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.3.2"
    hash = "sha256-DXatyiX9ogzKRld7ZcXAmDoP9qk8WLNdzg/ioNhppWg="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.5.2"
    hash = "sha256-jpkHZwHwQBTWOKKkCkr4WcUxfi19rWc5dZd0YbZiN5I="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssm"]
    version = "v1.35.0"
    hash = "sha256-U9QIDZJacIAwbzGz402whe5TVBZdn6ov73XgdfLFyhQ="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.6.2"
    hash = "sha256-8nCnEZ0Tw5H4N3wbO/ZQSwF/E7DeLeXFk0dghXuvJrk="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.11.1"
    hash = "sha256-uthCkAtI+5lVrIZKwhtkb1zHki9Z98lXuO0+sB4624o="
  [mod."github.com/aws/smithy-go"]
    version = "v1.13.5"
    hash = "sha256-lu1UnvPnLzXjDPBk2FJ4ZImKRQf7aj43mLbuolFdE64="
  [mod."github.com/bwmarrin/discordgo"]
    version = "v0.27.0"
    hash = "sha256-MP3FbpM2v+fYKzxMYF1A9uwfs6E3LBu+7bYoiVzZirY="
  [mod."github.com/chai2010/webp"]
    version = "v1.1.1"
    hash = "sha256-fgqfaEmrjMRcUC6WXVISIujzGYauZTKDDrJGLodn70c="
  [mod."github.com/codahale/hdrhistogram"]
    version = "v0.0.0-20161010025455-3a0bb77429bd"
    hash = "sha256-p9BZ4OPNXcssJwM1k6pSvcVADXonNr6YSMH3Jd27Vf0="
  [mod."github.com/coreos/go-iptables"]
    version = "v0.6.0"
    hash = "sha256-hB+9XsybJuEFozAXo+G8+2qMMZGoqBbMmSwmcNJgmSU="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.1"
    hash = "sha256-3IWhzlxuMQIQzhTYUT6SiToBjOzR9kfyoDCh1EetqgQ="
  [mod."github.com/eaburns/peggy"]
    version = "v0.0.0-20190420135231-b61cdde6efe6"
    hash = "sha256-qw1BOwQb4JOqmAZ1IYcKE/QxRUed6S9HeqH0rBRTmUI="
  [mod."github.com/eaburns/pretty"]
    version = "v0.0.0-20190404101635-2e1d2550ef0b"
    hash = "sha256-WIringh6P74e97dxJtR9XEmcPWZLpfISwfTiMvY6xhQ="
  [mod."github.com/facebookgo/ensure"]
    version = "v0.0.0-20160127193407-b4ab57deab51"
    hash = "sha256-jdCvva9KDH6KTTAtW0fBNw67xd0DhxLQbxU8PdhWLKY="
  [mod."github.com/facebookgo/stack"]
    version = "v0.0.0-20160209184415-751773369052"
    hash = "sha256-o6JL8oyrSBcgbdkvjUi4PT5OnfwgyXgbPQDA82sB2R8="
  [mod."github.com/facebookgo/subset"]
    version = "v0.0.0-20150612182917-8dac2c3c4870"
    hash = "sha256-Ub0cBFwF6MBzTZ7fpqxrC375arBv+au5I/LLzksVzE8="
  [mod."github.com/fogleman/gg"]
    version = "v1.3.0"
    hash = "sha256-Fs2JI0FmF4N5EzXJzGAPZMxZxo6wKyebkN/iBZ9sdNo="
  [mod."github.com/fogleman/primitive"]
    version = "v0.0.0-20190214200932-673f57e7b1b5"
    hash = "sha256-NZXofijequzro65PsoEaJCfDEFegB7tYKPgQHAc1F1U="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.4.0"
    hash = "sha256-LwOrfDN5fx/R2lgaD90RIu2NxcJDpyqYEURLc9Kgxgw="
  [mod."github.com/garyburd/redigo"]
    version = "v1.6.4"
    hash = "sha256-CHBFW/M79U58cq/NldC0Hk3a6uNNqNzCQ2X8RMLJAXc="
  [mod."github.com/go-interpreter/wagon"]
    version = "v0.6.0"
    hash = "sha256-FjHbE3POzCuIYThN7VPtTnG67JVCic6NIYjRjYRy0Gc="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.2.6"
    hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.0.6"
    hash = "sha256-fpaNRLf+qZy6Sk3Uas2H9fpxkVNkOCY1EcHcIZCAPr8="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/btree"]
    version = "v1.0.1"
    hash = "sha256-1PIeFGgUL4BK/StL/D12pg9bEQ5HfMT/fMLdus4pZTs="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.8"
    hash = "sha256-8zkIo+Sr1NXMnj3PNmvjX2sZKnAKWXOFvmnX7D9bwxQ="
  [mod."github.com/google/go-github"]
    version = "v17.0.0+incompatible"
    hash = "sha256-5EGZnkefwLCEODLICIgaq39UoOzBJqpeLraoc2hJfM8="
  [mod."github.com/google/go-querystring"]
    version = "v1.0.0"
    hash = "sha256-n0ewWuB/JYt8bfrefQHRJ9uak9QzXeQs68TW7fESgXY="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hdevalence/ed25519consensus"]
    version = "v0.0.0-20220222234857-c00d1f31bab3"
    hash = "sha256-1ec2xc7l9oNtWJwVtx14HnozMZCe2DpfXmu1xI1Z/yo="
  [mod."github.com/hullerob/go.farbfeld"]
    version = "v0.0.0-20181222022525-3661193c725f"
    hash = "sha256-vUAM6JDuNV+W8bhOcY8lqZVevdQ7nIl7lwwntRBo/Sw="
  [mod."github.com/illarion/gonotify"]
    version = "v1.0.1"
    hash = "sha256-73KDUfk5iNo12u+nNN2H4UTfJ1FlLifahnFNPzV1P/k="
  [mod."github.com/insomniacslk/dhcp"]
    version = "v0.0.0-20221215072855-de60144f33f8"
    hash = "sha256-JQgazr5CA3BLhaEcM5pKHamVummhhWu6DIrvDm9UA4g="
  [mod."github.com/jaytaylor/html2text"]
    version = "v0.0.0-20190408195923-01ec452cbe43"
    hash = "sha256-nnfxxHzCx8cEPQn3dixkq6/UwzC4vYb9OLJQWReouu8="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/joeshaw/envdecode"]
    version = "v0.0.0-20180312135643-c9e015854467"
    hash = "sha256-C7vaQXdsB/Yrz1LoAlK3tTIQjWgN8zRpCvN3MIyfv4U="
  [mod."github.com/joho/godotenv"]
    version = "v1.4.0"
    hash = "sha256-iD9pqyGcIdyWdScatPxBihf+wfPmqxOQRWVBv1OBZoA="
  [mod."github.com/josharian/native"]
    version = "v1.0.1-0.20221213033349-c1e37c09b531"
    hash = "sha256-0rMsNq1ugMn/8nX2ChEHxuzUPxiWOInplNiAPNj3RPE="
  [mod."github.com/jsimonetti/rtnetlink"]
    version = "v1.1.2-0.20220408201609-d380b505068b"
    hash = "sha256-xHfsLwbycxNNyFI9zTfSMsb2T35BKEWyW6Fmk1tDWM4="
  [mod."github.com/kballard/go-shellquote"]
    version = "v0.0.0-20180428030007-95032a82bc51"
    hash = "sha256-AOEdKETBMUC39ln6jBJ9NYdJWp++jV5lSbjNqG3dV+c="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.4"
    hash = "sha256-U6v9tYD16Tep9PuqRwCjrzXfj1IfV3KB54Qwnzko+xY="
  [mod."github.com/kortschak/wol"]
    version = "v0.0.0-20200729010619-da482cc4850a"
    hash = "sha256-lnr9r/KNv4EeeNohFImC3Vd5E9nJ0N+4ZZ0VHFjwHps="
  [mod."github.com/kr/pretty"]
    version = "v0.3.1"
    hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.13"
    hash = "sha256-93AwJFA8B2pwNJAPe64yN0c/CwkJNGFDWFe/HpzDVuk="
  [mod."github.com/mdlayher/genetlink"]
    version = "v1.2.0"
    hash = "sha256-7PGwKlBVkNsYZFErVsOzqmQ+tZnxqzpNd4LuzXjwNQU="
  [mod."github.com/mdlayher/netlink"]
    version = "v1.6.0"
    hash = "sha256-hFm39JacQH6ed6l/Xn10eP8pFVO0BK8a9phdgtj89f8="
  [mod."github.com/mdlayher/sdnotify"]
    version = "v1.0.0"
    hash = "sha256-O7MJt6Bam2bUoede07Z1T6EtW+kCJ+/4dJtYopZct1s="
  [mod."github.com/mdlayher/socket"]
    version = "v0.2.3"
    hash = "sha256-EDaSQ621SJ2OK2WycMtybuJ2KpaH86JHknqsiduuCtQ="
  [mod."github.com/miekg/dns"]
    version = "v1.1.50"
    hash = "sha256-mtf3QAk46pCA0a1K+oH6a7oqsY6LR6Qr8HD4qnDqe+s="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mmikulicic/stringlist"]
    version = "v1.0.0"
    hash = "sha256-0PcPNhzBD2itBlO9DS/oiz5uvmpXKXS1ukIupyPtpH0="
  [mod."github.com/mndrix/golog"]
    version = "v0.0.0-20170330170653-a28e2a269775"
    hash = "sha256-JD5kY0Krc1yHXT+0b3XzkwqFKpIvY3VFSok4/yHGOP8="
  [mod."github.com/mndrix/ps"]
    version = "v0.0.0-20170330174427-18e65badd6ab"
    hash = "sha256-Q9skxtyqOwkBxmUnzNCfbn813vPbqvwuAihwq/wkKs4="
  [mod."github.com/olekukonko/tablewriter"]
    version = "v0.0.5"
    hash = "sha256-/5i70IkH/qSW5KjGzv8aQNKh9tHoz98tqtL0K2DMFn4="
  [mod."github.com/otiai10/copy"]
    version = "v1.9.0"
    hash = "sha256-JKRqb4hfnYjglrsF9WikEZup8zIcV7Au854Sn+nJagU="
  [mod."github.com/peterh/liner"]
    version = "v1.2.2"
    hash = "sha256-F+cIfbpR/xQ3ODf5srpfJxLYIdgSHVc6YK16oKSqAEM="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/posener/complete"]
    version = "v1.2.3"
    hash = "sha256-/17KFHD0SsGALg9iLXNIdvVFcotOO+H6bOOD5SY0MVs="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.9.0"
    hash = "sha256-XKmbu8l55XGrvC20j8jocpauwZsdbP83YAwH79BEAC4="
  [mod."github.com/rs/cors"]
    version = "v1.8.3"
    hash = "sha256-VgVB4HKAhPSjNg96mIEUN1bt5ZQng8Fi3ZABy3CDWQE="
  [mod."github.com/sebest/xff"]
    version = "v0.0.0-20210106013422-671bd2870b3a"
    hash = "sha256-t7Gdp7S71Koej5Njg3jOo5vwyj02tJCbJjrq/vZGOho="
  [mod."github.com/sendgrid/rest"]
    version = "v2.4.1+incompatible"
    hash = "sha256-tV8BIe7lmGRI0gIuviJnXq2G2HGZBDrvHbGtHW5/bMs="
  [mod."github.com/ssor/bom"]
    version = "v0.0.0-20170718123548-6386211fdfcf"
    hash = "sha256-jYYzaIOaUFv575h3Sz/T4DPO6EWFRwEpwx1zF00i5SU="
  [mod."github.com/tailscale/certstore"]
    version = "v0.1.1-0.20220316223106-78d6e1c49d8d"
    hash = "sha256-qBlCkpHp8t+XNwMOJRO+YpvXn0nOJMABjUZKH70b/Y0="
  [mod."github.com/tailscale/golang-x-crypto"]
    version = "v0.0.0-20221102133106-bc99ab8c2d17"
    hash = "sha256-yEJ1IYQkly+QBtPZqVevLypHs7Yi04y8uN+Uevn9D2U="
  [mod."github.com/tailscale/goupnp"]
    version = "v1.0.1-0.20210804011211-c64d0f06ea05"
    hash = "sha256-PRMJcYY+wjpbHkC9dQWTPErh2ID29UnFxehxmYR704I="
  [mod."github.com/tailscale/netlink"]
    version = "v1.1.1-0.20211101221916-cabfb018fe85"
    hash = "sha256-bMK5qqObMcxIbPy5XhOZP8TGDaXvDAHsE0FR68VMLi8="
  [mod."github.com/tailscale/wireguard-go"]
    version = "v0.0.0-20221219190806-4fa124729667"
    hash = "sha256-ds+3T5m9CDZNQXqxw0ECFoQhAbOrmw2TbqLc/jRVuJ0="
  [mod."github.com/tcnksm/go-httpstat"]
    version = "v0.2.0"
    hash = "sha256-bCWn8E+DcZY6+yPu07AF3hCcDZx3CFdD74qfpDIgVqI="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.0.0-pre.7"
    hash = "sha256-CJMdOaju5ooTtNnNFAF7hbPH8859tGNF4QIYbkOOLPM="
  [mod."github.com/tmc/scp"]
    version = "v0.0.0-20170824174625-f7b48647feef"
    hash = "sha256-qHwQb3JA43VVhJdB18/2zXbxqW/bgw1yvr8YhqFyd74="
  [mod."github.com/u-root/uio"]
    version = "v0.0.0-20221213070652-c3537552635f"
    hash = "sha256-Y92dH3Jqq0WbdO7Isr6EZSFisnUQ/T89R6t6DiAIt3E="
  [mod."github.com/vishvananda/netlink"]
    version = "v1.1.1-0.20211118161826-650dca95af54"
    hash = "sha256-5PQbPfcgUP3HgLMQtPQxpvD0ebsZE0iiGGlG6z9FSKI="
  [mod."github.com/vishvananda/netns"]
    version = "v0.0.0-20211101163701-50045581ed74"
    hash = "sha256-B5BcBbKh/XD0baExSidXZZGPzQccsOrOmdUMUAE6VU0="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.6"
    hash = "sha256-DenVAmyN22xUiivk6fdJp4C9ZnUJXCMDUf8E0goRRV4="
  [mod."go4.org"]
    version = "v0.0.0-20190313082347-94abd6928b1d"
    hash = "sha256-/hCsgDZzSnd5kPI5u6diLud6sEZm9e+tyCMVFRy5O1k="
  [mod."go4.org/mem"]
    version = "v0.0.0-20210711025021-927187094b94"
    hash = "sha256-njyZb6Ml+5YJXz4ott30xvNZej2BY30izyH34PiTkWU="
  [mod."go4.org/netipx"]
    version = "v0.0.0-20220725152314-7e7bdc8411bf"
    hash = "sha256-mw2+5uHhfeJsjZrezMcLuiLvsZJ8wz5Z3tJcxq2j+bE="
  [mod."golang.org/x/crypto"]
    version = "v0.3.0"
    hash = "sha256-Un9wPqz8u/xpV98T4IqE6RMXIPhGCIm2prsNkHP3cjg="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20221205204356-47842c84f3db"
    hash = "sha256-HWHDTTbsKZp1bMN06ZKluiLt8Yfjtnf1XhR9GWp4rQk="
  [mod."golang.org/x/exp/errors"]
    version = "v0.0.0-20190510132918-efd6b22b2522"
    hash = "sha256-o7NXNX8GJhkjUEiHzTBmDthOL83GUs3oGFjRx4bLi9M="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20211028202545-6944b10bf410"
    hash = "sha256-NblRNocJ+PrKVyU+nBS8eac3jRPx8MT17Jfv3kxrS2o="
  [mod."golang.org/x/mod"]
    version = "v0.6.0"
    hash = "sha256-qaHIt9MYuTTfaKtbeVqBVI+Pcv60SMQuhkkjFQObx48="
  [mod."golang.org/x/net"]
    version = "v0.5.0"
    hash = "sha256-HpbIAiLs7S1+tVsaSSdbCPw1IK43A0bFFuSzPSyjLbo="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20220411215720-9780585627b5"
    hash = "sha256-PubcNZWej7Pb8TnHNfXPkRo3Gj91YfePvvN5ImftEbs="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.4.0"
    hash = "sha256-jchMzHCH5dg+IL/F+LqaX/fyAcB/nvHQpfBjqwaRJH0="
  [mod."golang.org/x/term"]
    version = "v0.4.0"
    hash = "sha256-wQKxHV10TU4vCU8Re2/hFmAbur/jRWEOB8QXBzgTFNY="
  [mod."golang.org/x/text"]
    version = "v0.6.0"
    hash = "sha256-+bpeRWR3relKACdal6NPj+eP5dnWCplTViArSN7/qA4="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20220609170525-579cf78fd858"
    hash = "sha256-RvtDynrcuBy8xu4Vtg30cbyS0QUxyBfDVoQ7rqbR82Q="
  [mod."golang.org/x/tools"]
    version = "v0.2.0"
    hash = "sha256-T6+3oa41rN1o7izlmV2pHqON3f4mw7hjYC/GMjzPqc8="
  [mod."golang.zx2c4.com/wintun"]
    version = "v0.0.0-20211104114900-415007cec224"
    hash = "sha256-8f4qqrYK1sobCgUXrCteMyv4s8cT0T+6c0l1ZBiADL4="
  [mod."golang.zx2c4.com/wireguard/windows"]
    version = "v0.5.3"
    hash = "sha256-wcJWS/4Fqbc+1RHSntex0zBdlHiZfzrea4QabYkNKvU="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.0"
    hash = "sha256-p1cVM3OeEErh1WeNRAg4n3zYm/0qPTPmIiWNjRmJiMQ="
  [mod."gopkg.in/tucnak/telebot.v2"]
    version = "v2.0.0-20190415090633-8c1c512262f2"
    hash = "sha256-Z5toFOhdxupU6Y88pdw5qP8uh2eO3v8WPp4ttPMZhIs="
  [mod."gvisor.dev/gvisor"]
    version = "v0.0.0-20221203005347-703fd9b7fbc0"
    hash = "sha256-XB0g1a3IJzmM+R3BUCIA/C3wGUQGoBhGZxEcU6JGqqI="
  [mod."inet.af/peercred"]
    version = "v0.0.0-20210906144145-0893ea02156a"
    hash = "sha256-f0ws9PdTpRpX64asTol0O82IWYM9r8NhZgOCi2dPToo="
  [mod."nhooyr.io/websocket"]
    version = "v1.8.7"
    hash = "sha256-6pQ35gFvbyMhNo0gv4bPxYDUrwDF/ok1GMA+BHfsRRM="
  [mod."tailscale.com"]
    version = "v1.36.0"
    hash = "sha256-izu18Q/iXqEr8stVnGNlwxCXIfXaf3LtnH57cr1oCOs="
  [mod."tulpa.dev/cadey/jvozba"]
    version = "v0.0.0-20200326200349-f0ebe310be06"
    hash = "sha256-0rP0rdwDp8C+hHlM/Cgp+4YGZRm2y7jgRKFOsWYRKUQ="
  [mod."within.website/johaus"]
    version = "v1.1.0"
    hash = "sha256-iUfbQME/rIpSJUfAYQMybLL73Cf4WQ03kDR0/I7pbdI="
  [mod."within.website/ln"]
    version = "v0.9.1"
    hash = "sha256-JcRR0SX3XzatjnZ+yho04VvJGqXvZr5zK50AUS99wmY="
