apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "arch-linux"
  namespace: waifud
  annotations:
    xeiaso.net/project: waifud
spec:
  storage:
    storageClassName: longhorn
    volumeMode: block # or filesystem
    accessModes:
      - ReadWriteOnce # Necessary as it's no longer has a default
    resources:
      requests:
        storage: 2Gi
  source:
    http:
      url: "https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2"
