apiVersion: v1
kind: Service
metadata:
  name: within-website
  labels:
    app.kubernetes.io/name: within-website
spec:
  selector:
    app.kubernetes.io/name: within-website
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
