apiVersion: v1
kind: Pod
metadata:
  name: gitea-data-migrator
  namespace: gitea
  labels:
    name: gitea-data-migrator
spec:
  volumes:
  - name: old
    persistentVolumeClaim:
      claimName: gitea
  - name: new
    persistentVolumeClaim:
      claimName: gitea-old-data
  - name: 22gi
    persistentVolumeClaim:
      claimName: gitea-22gi
  - name: return-of-samus
    persistentVolumeClaim:
      claimName: gitea-2-return-of-samus
  containers:
  - name: gitea-data-migrator
    image: alpine:edge
    args:
    - sleep
    - infinity
    volumeMounts:
    - name: old
      mountPath: /pvc/old
    - name: new
      mountPath: /pvc/new
    - name: 22gi
      mountPath: /pvc/22gi
    - name: return-of-samus
      mountPath: /pvc/return-of-samus
