apiVersion: v1
kind: ConfigMap
metadata:
  name: "gitea"
data:
  USER: git
  USER_UID: "1000"
  USER_GID: "1000"

  # GITEA__storage__STORAGE_TYPE: minio
  GITEA__storage__STORAGE_TYPE: local
  GITEA__storage__SERVE_DIRECT: "true"
  GITEA__storage__MINIO_ENDPOINT: minio.xeserv.us
  GITEA__storage__MINIO_BUCKET: gitea
  GITEA__storage__MINIO_USE_SSL: "true"
  GITEA__storage__MINIO_ACCESS_KEY_ID: "qI118JbfKI7jSoIODniy"
  GITEA__stroage__MINIO_SECRET_ACCESS_KEY: "dIOfpszdPDKLurcppvic68TJcscZ4NZbgJr30RaX"
  GITEA__service__DISABLE_REGISTRATION: "false"
  GITEA__service__REGISTER_MANUAL_CONFIRM: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    xeiaso.net/thing: http
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  replicas: 1
  selector:
    matchLabels:
      xeiaso.net/thing: http
  template:
    metadata:
      labels:
        xeiaso.net/thing: http
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea
        - name: internal-certs
          secret:
            secretName: gitea-internal-tls
      containers:
        - name: main
          image: gitea/gitea:1-rootless
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - configMapRef:
                name: gitea
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ssh
              containerPort: 2222
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
              subPath: data
            - name: data
              mountPath: /etc/gitea
              subPath: conf
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
        - name: relayd
          image: ghcr.io/xe/x/relayd:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BIND
              value: ":8443"
            - name: PROXY_TO
              value: "http://localhost:3000"
          volumeMounts:
            - name: "internal-certs"
              mountPath: "/xe/pki"
              readOnly: true
