apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gitea
spec:
  endpoints:
    - dnsName: git.xeserv.us
      recordTTL: 3600
      recordType: A
      targets:
        - 10.219.80.171
