resources:
  - namespace.yaml
  - pvc.yaml
  - 1password.yaml
  - deployment.yaml
  - onionservice.yaml
  - service.yaml
  - runner.yaml
  #- external-dns.yaml
  - ingress.yaml
namespace: gitea

configMapGenerator:
- name: anubis-cfg
  behavior: create
  files:
  - ./cfg/anubis/botPolicies.json