resources:
  - namespace.yaml
  - pvc.yaml
  - 1password.yaml
  - deployment.yaml
  - onionservice.yaml
  - service.yaml
  - runner.yaml
  #- external-dns.yaml
  - ingress.yaml
  - valkey.yaml
namespace: gitea

configMapGenerator:
  - name: anubis-cfg
    behavior: create
    files:
      - ./cfg/anubis/botPolicies.yaml

  - name: botstopper-custom-css
    behavior: create
    files:
      - ./cfg/botstopper/custom.css

  - name: gitea-runner-cfg
    behavior: create
    files:
      - ./cfg/runner/config.yaml
