apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: git
spec:
  version: 3
  rules:
    - port:
        number: 22
        name: ssh
      backend:
        service:
          name: git
          port:
            name: ssh
            number: 22
    - port:
        number: 80
        name: http
      backend:
        service:
          name: git
          port:
            name: http
            number: 80
