apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-2-return-of-samus
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 130Gi
