apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi