apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: runner-secret
spec:
  itemPath: "vaults/Kubernetes/items/Gitea Runner Secrets"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-config
data:
  daemon.json: |
    {
      "registry-mirrors": ["https://pt-dh.int.xeserv.us"]
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: act-runner
  name: act-runner
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: act-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: act-runner
    spec:
      restartPolicy: Always
      volumes:
        - name: docker-certs
          emptyDir: {}
        - name: runner-data
          emptyDir: {}
        - name: docker-daemon-config
          configMap:
            name: docker-daemon-config
        - name: gitea-runner-cfg
          configMap:
            name: gitea-runner-cfg
      containers:
        - name: runner
          image: gitea/act_runner:nightly-dind
          imagePullPolicy: Always
          env:
            - name: CONFIG_FILE
              value: "/etc/gitea-runner/config.yaml"
            - name: GITEA_INSTANCE_URL
              value: http://git.gitea.svc.alrest.xeserv.us
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: runner-secret
                  key: token
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: runner-data
              mountPath: /data
              subPath: "actions"
            - name: docker-daemon-config
              mountPath: "/etc/docker"
            - name: gitea-runner-cfg
              mountPath: "/etc/gitea-runner"
