apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
stringData:
  token: "CY2fOnh2aP4scVZc9w4dEDkyxBGnsezNZqRWcKyi"
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: act-runner
  name: act-runner
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: act-runner
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: act-runner
    spec:
      restartPolicy: Always
      volumes:
      - name: docker-certs
        emptyDir: {}
      - name: runner-data
        emptyDir: {}
      containers:
      - name: runner
        image: gitea/act_runner:nightly-dind-rootless
        imagePullPolicy: Always
        env:
        - name: GITEA_INSTANCE_URL
          value: http://git.gitea.svc.alrest.xeserv.us
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: runner-secret
              key: token
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: runner-data
          mountPath: /data
          subPath: "actions"