apiVersion: v1
kind: Service
metadata:
  name: yanna
  namespace: waifud
spec:
  type: ClusterIP
  selector:
    kubevirt.io/domain: yanna
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: http-alt
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-dev
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: https-alt
      port: 8443
      targetPort: 8443
      protocol: TCP
