apiVersion: v1
kind: Service
metadata:
  name: glance
spec:
  selector:
    app: glance
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8443
      name: https
