# fly.toml app configuration file generated for mimi on 2024-01-30T20:17:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mimi"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"

swap_size_mb = 512

vm.size = "shared-cpu-2x"
vm.memory = 1024

[build]
image = "registry.fly.io/mimi:latest"

[[services]]
protocol = "tcp"
internal_port = 9002
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
