apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: itsuki
  resources:
    requests:
      storage: 2Gi
