apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ollama
  labels:
    xeiaso.net/project: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ssd"
  resources:
    requests:
      storage: 64Gi
