apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: files-xeiaso-net-cname
spec:
  endpoints:
  - dnsName: "files.xeiaso.net"
    recordTTL: 3600
    recordType: CNAME
    targets:
    - files.xeiaso.net.fly.storage.tigris.dev