apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000 # kubelet chowns the volume to this GID + sets setgid
  initContainers:
    - name: stat-data
      image: busybox
      command: ["sh", "-c", "stat /data"]
      volumeMounts:
        - { name: data, mountPath: /data }
    - name: init-touch
      image: busybox
      command: ["sh", "-c", "touch /data/foo"]
      volumeMounts:
        - { name: data, mountPath: /data }
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - { name: data, mountPath: /data }
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-data
