apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: saga-xe-x
  namespace: arc-runners
spec:
  chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  targetNamespace: arc-runners
  valuesContent: |-
    githubConfigUrl: https://github.com/Xe/x
    githubConfigSecret: xe-arc-creds

    containerMode:
      type: "dind"
