apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aws-creds
  namespace: external-dns
spec:
  itemPath: "vaults/lc5zo4zjz3if3mkeuhufjmgmui/items/3xn7uf73xnzholrfk6tla5rhpa"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aws-creds
  namespace: cert-manager
spec:
  itemPath: "vaults/lc5zo4zjz3if3mkeuhufjmgmui/items/3xn7uf73xnzholrfk6tla5rhpa"