apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-ingress
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-ingress
  template:
    metadata:
      labels:
        app: external-dns-ingress
    spec:
      serviceAccountName: external-dns
      containers:
      - name: ingress
        image: registry.k8s.io/external-dns/external-dns:v0.15.0
        args:
        - --source=ingress
        - --default-targets=155.138.132.228
        - --provider=aws
        - --registry=dynamodb
        - --dynamodb-region=ca-central-1
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY