apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: me@xeiaso.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-acme-key
    solvers:
      - dns01:
          route53:
            region: ca-central-1
            accessKeyIDSecretRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY