apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nekomata
spec:
  endpoints:
    - dnsName: nekomata.within.lgbt
      recordTTL: 3600
      recordType: A
      targets:
        - 195.26.244.235
    - dnsName: nekomata.within.lgbt
      recordTTL: 3600
      recordType: AAAA
      targets:
        - 2605:a140:2244:0333::1
