apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale
data:
  HEADSCALE_DATABASE_SQLITE_PATH: /etc/headscale/db.sqlite
  HEADSCALE_DATABASE_TYPE: sqlite3
  HEADSCALE_DERP_AUTO_UPDATE_ENABLED: "true"
  HEADSCALE_DERP_UPDATE_FREQUENCY: 24h
  HEADSCALE_DERP_URLS: https://controlplane.tailscale.com/derpmap/default
  HEADSCALE_DNS_BASE_DOMAIN: int.within.lgbt
  HEADSCALE_DNS_MAGIC_DNS: "true"
  HEADSCALE_DNS_CONFIG_NAMESERVERS_GLOBAL: "1.1.1.1 8.8.8.8"
  HEADSCALE_DISABLE_CHECK_UPDATES: "true"
  HEADSCALE_EPHEMERAL_NODE_INACTIVITY_TIMEOUT: 30m
  HEADSCALE_PREFIXES_V4: "100.64.0.0/10"
  HEADSCALE_PREFIXES_V6: "fd7a:115c:a1e0::/48"
  HEADSCALE_PREFIXES_ALLOCATION: "random"
  HEADSCALE_LISTEN_ADDR: "0.0.0.0:8000"
  HEADSCALE_METRICS_LISTEN_ADDR: "0.0.0.0:9090"
  HEADSCALE_NOISE: "{}"
  HEADSCALE_NOISE_PRIVATE_KEY_PATH: "/etc/headscale/noise_private.key"
  HEADSCALE_PRIVATE_KEY_PATH: "/etc/headscale/private.key"
  HEADSCALE_SERVER_URL: "https://hs.xeserv.us"
  HEADSCALE_OIDC_ONLY_START_IF_OIDC_IS_AVAILABLE: "true"
  HEADSCALE_OIDC_STRIP_EMAIL_DOMAIN: "true"
