app = "xe-robocadey2"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  strategy = "immediate"

[build]
  image = "registry.fly.io/xe-robocadey2:latest"

[env]
  STATE = "/data/robocadey2"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source="robocadey2_state"
  destination="/data"

[metrics]
port = 8080
path = "/.within/metrics"
