apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      team: within
  podMonitorSelector:
    matchLabels:
      team: within
  alerting:
    alertmanagers:
      - namespace: default
        name: alertmanager-example
        port: web
