apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerial
  annotations:
    operator.1password.io/auto-restart: "true"
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
  labels:
    app.kubernetes.io/name: aerial
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aerial
  replicas: 1
  template:      
    metadata:
      labels:
        app.kubernetes.io/name: aerial
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bot
          image: ghcr.io/xe/x/aerial:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: aerial