apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocket-id
  labels:
    name: pocket-id
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "512k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - idp.xeserv.us
      secretName: idp-xeserv-us-public-tls
  rules:
    - host: idp.xeserv.us
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pocket-id
                port:
                  name: http
