apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    installCRDs: true
    prometheus:
      enabled: false
    nodeSelector:
      role: edge
    tolerations:
      - key: dedicated
        operator: Equal
        value: edge
        effect: NoSchedule
    webhook:
      nodeSelector:
        role: edge
      tolerations:
        - key: dedicated
          operator: Equal
          value: edge
          effect: NoSchedule
    cainjector:
      nodeSelector:
        role: edge
      tolerations:
        - key: dedicated
          operator: Equal
          value: edge
          effect: NoSchedule
    startupapicheck:
      nodeSelector:
        role: edge
      tolerations:
        - key: dedicated
          operator: Equal
          value: edge
          effect: NoSchedule
