kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rotational
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "480" # 8 hours in minutes
  diskSelector: "rotational"
  fromBackup: ""                      
  fsType: "ext4"                      
  dataLocality: "disabled"            
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"      
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "480" # 8 hours in minutes
  diskSelector: "ssd"
  fromBackup: ""                      
  fsType: "ext4"                      
  dataLocality: "disabled"            
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: yolo
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480" # 8 hours in minutes
  diskSelector: "rotational"
  fromBackup: ""                      
  fsType: "ext4"                      
  dataLocality: "disabled"            
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"