apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hlang-christine-website
  labels:
    app.kubernetes.io/name: hlang
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - h.christine.website
      secretName: hlang-christine-website-public-tls
  rules:
  - host: h.christine.website
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port: 
              number: 8080