---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapientwindex
  labels:
    app.kubernetes.io/name: sapientwindex
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sapientwindex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sapientwindex
    spec:
      containers:    
        - name: bot
          image: ghcr.io/xe/x/sapientwindex:latest
          env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: sapientwindex
                  key: DISCORD_WEBHOOK_URL
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sapientwindex
spec:
  itemPath: "vaults/lc5zo4zjz3if3mkeuhufjmgmui/items/cqervqahekvmujrlhdaxgqaffi"