apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: penelope-wildcard
spec:
  endpoints:
    - dnsName: "*.penelope.within.lgbt"
      recordTTL: 3600
      recordType: A
      targets:
        - 100.90.105.81
    - dnsName: "*.penelope.within.lgbt"
      recordTTL: 3600
      recordType: AAAA
      targets:
        - fd7a:115c:a1e0:8952:be9f:4a65:92c9:fec8
