apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pkgs-techaro-lol-cname
spec:
  endpoints:
  - dnsName: "pkgs.techaro.lol"
    recordTTL: 3600
    recordType: CNAME
    targets:
    - pkgs.techaro.lol.fly.storage.tigris.dev