apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9000
      protocol: TCP
    - name: webui
      port: 8080
      targetPort: 9001
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9001
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8444
      protocol: TCP
  selector:
    app: minio
