apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9000
      protocol: TCP
    - name: webui
      port: 8080
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio