apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-internal
  namespace: default
spec:
  secretName: registry-internal-tls

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - registry.int.xeserv.us
  issuerRef:
    name: "letsencrypt-prod"
    kind: ClusterIssuer
    group: cert-manager.io
