apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: registry-internal
spec:
  endpoints:
    - dnsName: registry.int.xeserv.us
      recordTTL: 3600
      recordType: A
      targets:
        - 10.223.208.190