[package]
name = "mastosan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lol_html = "1.0"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

