apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
      envoyDeployment:
        pod:
          nodeSelector:
            role: edge
          tolerations:
            - key: dedicated
              operator: Equal
              value: edge
              effect: NoSchedule
