apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: arc
  namespace: kube-system
spec:
  chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  targetNamespace: arc-systems
  createNamespace: true
