apiVersion: apps/v1
kind: Deployment
metadata:
  name: faster-whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faster-whisper
  template:
    metadata:
      labels:
        app: faster-whisper
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        xeiaso.net/gpu: rtx2060-6gb
      containers:
      - name: main
        image: fedirz/faster-whisper-server:latest-cuda
        ports:
        - containerPort: 8000