.Dd December 09, 2018
.Dt LICENSE 1 URM


.Sh NAME
.Nm license
.Nd Generate software licenses from a rather large list of templates.


.Sh SYNOPSIS
.Nm
.Op Fl email
.Op Fl license
.Op Fl name
.Op Fl out
.Op Fl show


.Sh DESCRIPTION
.Nm
is a software license generator. It uses
.Xr git-config 1
to parse out your email and "real name" when relevant for the license template reasons.


.Bl -tag -width " " -offset indent -compact


.It Fl email
The email of the person licensing the software. This should be your email, or a corporation's email. If in doubt, ask a lawyer what to put here.

The default value for this is derived from
.Xr git-config 1
by using the command:

.Li $ git config user.email

.It Fl license
If set,
.Nm
will show its software license details and then exit.

.It Fl name
The name of the person licensing the software. This should be your name, or a corporation's name. If in doubt, ask a lawyer what to put here.

The default value for this is derived from
.Xr git-config 1
by using the command:

.Li $ git config user.name

.It Fl out
If this is set,
.Nm
will write the resulting license to the disk instead of standard out.

.It Fl show
If set,
.Nm
will show its list of license templates instead of generating one.

.El


.Sh EXAMPLES

.Li license

.Li license -license

.Li license -show

.Li license mit


.Sh DIAGNOSTICS

.Ex -std license
