apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: markdownlang-telemetryd
  labels:
    app.kubernetes.io/name: markdownlang-telemetryd
    app.kubernetes.io/part-of: markdownlang
spec:
  itemPath: "vaults/Kubernetes/items/MarkdownLang Telemetry"
