// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)
