apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "arona"
  namespace: waifud
spec:
  storage:
    storageClassName: longhorn
    volumeMode: Block # or filesystem
    accessModes:
      - ReadWriteOnce # Necessary as it's no longer has a default
    resources:
      requests:
        storage: 64Gi
  source:
    http:
      url: "https://cloud-images.ubuntu.com/daily/server/noble/current/noble-server-cloudimg-amd64.img"
---
apiVersion: v1
kind: Service
metadata:
  name: arona
  namespace: waifud
spec:
  ports:
  # ssh
  - port: 22
    protocol: TCP
    targetPort: 22
    name: ssh
  # IRC relay
  - port: 12482
    protocol: TCP
    targetPort: 12482
    name: irc-relay
  # Weechat relay
  - port: 28945
    protocol: TCP
    targetPort: 28945
    name: weechat-relay
  selector:
    kubevirt.io/domain: "arona"
  type: ClusterIP
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: "arona"
  namespace: waifud
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: "arona"
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: "arona"
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: arona
            ssh_pwauth: True
            disable_root: false

            write_files:
              - encoding: b64
                content: bmV0d29yazoKICB2ZXJzaW9uOiAyCiAgZXRoZXJuZXRzOgogICAgaWQwOgogICAgICBkaGNwNDogdHJ1ZQogICAgICBtYXRjaDoKICAgICAgICBuYW1lOiBlbnAqCg==
                owner: root:root
                path: /etc/netplan/99-net-fix.yaml
                permissions: '0644'

            users:
              - name: xe
                groups: [ wheel ]
                sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
                shell: /bin/bash
                ssh-authorized-keys:
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6/+q2dBHEfETomAH7rvDPXHulSXnhcV/szxTAWiKZA cadey@defoko
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIH27tCTJZwJxp+bcWRALtrk7SqnwXZ4/Ae67jIO0eF cadey@shiroko
              - name: root
                groups: [ wheel ]
                sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
                shell: /bin/bash
                ssh-authorized-keys:
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6/+q2dBHEfETomAH7rvDPXHulSXnhcV/szxTAWiKZA cadey@defoko
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIH27tCTJZwJxp+bcWRALtrk7SqnwXZ4/Ae67jIO0eF cadey@shiroko
        name: cloudinitdisk