// Code generated by "stringer -type=Nanpa"; DO NOT EDIT.

package mainsa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Wan-1]
	_ = x[Tu-2]
	_ = x[Mute-3]
}

const _Nanpa_name = "WanTuMute"

var _Nanpa_index = [...]uint8{0, 3, 5, 9}

func (i Nanpa) String() string {
	i -= 1
	if i < 0 || i >= Nanpa(len(_Nanpa_index)-1) {
		return "Nanpa(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Nanpa_name[_Nanpa_index[i]:_Nanpa_index[i+1]]
}
