// Code generated by "stringer -type=Sike"; DO NOT EDIT.

package mainsa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kama-1]
	_ = x[Poka-2]
	_ = x[Monsi-3]
}

const _Sike_name = "KamaPokaMonsi"

var _Sike_index = [...]uint8{0, 4, 8, 13}

func (i Sike) String() string {
	i -= 1
	if i < 0 || i >= Sike(len(_Sike_index)-1) {
		return "Sike(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Sike_name[_Sike_index[i]:_Sike_index[i+1]]
}
