// Code generated by "stringer -type=Tawa"; DO NOT EDIT.

package mainsa

import "strconv"

const _Tawa_name = "KasiSeliSinLete"

var _Tawa_index = [...]uint8{0, 4, 8, 11, 15}

func (i Tawa) String() string {
	i -= 1
	if i < 0 || i >= Tawa(len(_Tawa_index)-1) {
		return "Tawa(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Tawa_name[_Tawa_index[i]:_Tawa_index[i+1]]
}
