apiVersion: v1
kind: Namespace
metadata:
  name: future-sight
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: future-sight
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2-alpine
          ports:
            - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: future-sight
spec:
  selector:
    app: nats
  ports:
    - port: 4222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-secret
  namespace: future-sight
  labels:
    app: valkey
data:
  VALKEY_PASSWORD: hunter2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: future-sight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: 'docker.io/bitnami/valkey:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: valkey-secret
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: future-sight
  labels:
    app: valkey
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: valkey
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tigris-creds
  namespace: future-sight
  labels:
    app.kubernetes.io/name: future-sight
spec:
  itemPath: "vaults/Kubernetes/items/Tigris creds"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: future-sight
  namespace: future-sight
  labels:
    app.kubernetes.io/name: future-sight
data:
  BUCKET_NAME: xesite-preview-versions
  DATA_DIR: /cache
  NATS_URL: nats://nats:4222
  VALKEY_HOST: valkey:6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: future-sight
  namespace: future-sight
  labels:
    app.kubernetes.io/name: future-sight
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: future-sight
  template:
    metadata:
      namespace: future-sight
      labels:
        app.kubernetes.io/name: future-sight
    spec:
      volumes:
        - name: tigris
          secret:
            secretName: tigris-creds
        - name: cache
          emptyDir: {}
      securityContext:
        fsGroup: 1000
      containers:
        - name: main
          image: ghcr.io/xe/x/future-sight:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: X-Kubernetes
                  value: "is kinda okay"
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: tigris
              mountPath: /run/secrets/tigris
            - name: cache
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: valkey-secret
            - configMapRef:
                name: future-sight
---
apiVersion: v1
kind: Service
metadata:
  name: future-sight
  namespace: future-sight
  labels:
    app.kubernetes.io/name: future-sight
spec:
  selector:
    app.kubernetes.io/name: future-sight
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: web
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: future-sight
  namespace: future-sight
  labels:
    app.kubernetes.io/name: future-sight
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - preview.xeiaso.net
      secretName: preview-xeiaso-net-tls
  rules:
  - host: preview.xeiaso.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: future-sight
            port: 
              name: web