---
apiVersion: v1
kind: Namespace
metadata:
  name: mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi
  namespace: mi
  labels:
    app.kubernetes.io/name: mi
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mi-bluesky
  namespace: mi
spec:
  itemPath: "vaults/Kubernetes/items/Bluesky xeiaso.net"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mi-mastodon
  namespace: mi
spec:
  itemPath: "vaults/Kubernetes/items/@cadey@pony.social token"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mi-irc
  namespace: mi
spec:
  itemPath: "vaults/Kubernetes/items/IRC [Mara]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi
  namespace: mi
  labels:
    app.kubernetes.io/name: mi
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mi
  template:
    metadata:
      namespace: mi
      labels:
        app.kubernetes.io/name: mi
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: mi
        - name: bluesky
          secret:
            secretName: mi-bluesky
        - name: irc
          secret:
            secretName: mi-irc
        - name: mastodon
          secret:
            secretName: mi-mastodon
      securityContext:
        fsGroup: 1000
      containers:
        - name: main
          image: ghcr.io/xe/x/mi:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9195
              httpHeaders:
                - name: X-Kubernetes
                  value: "is kinda okay"
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: BIND
              value: ":8080"
            - name: DB_LOC
              value: "/data/mi.db"
            - name: INTERNAL_BIND
              value: ":9195"
          volumeMounts:
            - name: vol
              mountPath: "/data"
            - name: bluesky
              readOnly: true
              mountPath: "/run/secrets/bluesky"
            - name: irc
              readOnly: true
              mountPath: "/run/secrets/irc"
            - name: mastodon
              readOnly: true
              mountPath: "/run/secrets/mastodon"
---
apiVersion: v1
kind: Service
metadata:
  name: mi
  namespace: mi
  labels:
    app.kubernetes.io/name: mi
spec:
  selector:
    app.kubernetes.io/name: mi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 9195
      targetPort: 9195
      name: metrics
  type: ClusterIP
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: public-http-auth
  namespace: mi
  labels:
    app.kubernetes.io/name: mi
spec:
  itemPath: "vaults/lc5zo4zjz3if3mkeuhufjmgmui/items/4ytaobocixjfaoje7rhrtidg4m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-public
  namespace: mi
  labels:
    app.kubernetes.io/name: mi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: public-http-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - mi.cetacean.club
      secretName: mi-public-tls
  rules:
  - host: mi.cetacean.club
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mi
            port: 
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-front-public
  namespace: mi
  labels:
    app.kubernetes.io/name: mi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/custom-headers: "mi-front-public-headers"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - home.cetacean.club
      secretName: home-cetacean-club-tls
  rules:
  - host: home.cetacean.club
    http:
      paths:
      - pathType: Prefix
        path: "/front"
        backend:
          service:
            name: mi
            port: 
              name: http
---
apiVersion: v1
data:
  Server: "within.website/x/cmd/mi + within.website/x/cmd/ingressd"
kind: ConfigMap
metadata:
  name: mi-front-public-headers
  namespace: mi
