name: Dependabot super yolo

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  run-custom-command:
    if: ${{ github.actor_id == '49699333' }} # Dependabot
    runs-on: alrest-x
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
      - name: Setup the GitHub CLI
        uses: actions4gh/setup-gh@v1.0.2
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ github.token }}
