name: Dependabot super yolo

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  run-custom-command:
    if: ${{ github.actor_id == '49699333' }} # Dependabot
    runs-on: alrest-x
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
      - name: Setup the GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          sudo mkdir -p -m 755 /etc/apt/keyrings
          out=$(mktemp) 
          wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg
          cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
          sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ github.token }}
