apiVersion: v1
kind: Service
metadata:
	apiVersion: v1
	kind: Service
	metadata:
		name: mosquitto
		labels:
			app: mosquitto
	spec:
		type: LoadBalancer
		selector:
			app: mosquitto
			tier: frontend
		ports:
			- name: mqtt
				port: 1883
				targetPort: 1883
---
	apiVersion: v1
	kind: PersistentVolumeClaim
	metadata:
		name: mq-pv-claim
		labels:
			app: mosquitto
	spec:
		accessModes:
			- ReadWriteOnce
		resources:
			requests:
				storage: 2Gi
---
	apiVersion: apps/v1
	kind: Deployment
	metadata:
		name: mosquitto
		labels:
			app: mosquitto
	spec:
		replicas: 1
		selector:
			matchLabels:
				app: mosquitto
				tier: frontend
		strategy:
			type: Recreate
		template:
			metadata:
				labels:
					app: mosquitto
					tier: frontend
			spec:
				containers:
					- name: mosquitto
						image: eclipse-mosquitto:latest
						ports:
							- name: mqtt
								containerPort: 1883
						volumeMounts:
							- name: mosquitto-persistent-storage
								mountPath: /mosquitto/data
							- name: mosquitto-config
								mountPath: /mosquitto/config/mosquitto.conf
								subPath: mosquitto.conf
							- name: mosquitto-password
								mountPath: /mosquitto/config/password.txt
								subPath: password.txt
				volumes:
					- name: mosquitto-persistent-storage
						persistentVolumeClaim:
							claimName: mq-pv-claim
					- name: mosquitto-config
						configMap:
							name: mosquitto-config
					- name: mosquitto-password
						configMap:
							name: mosquitto-password
